#import "/template/lib.typ": *

#show: cv.with(
  author: (
    firstname: "Jan",
    lastname: "Van Rensbergen",
    email: "jan.vanrensbergen@gmail.com",
    address: [Bergstraat 39, 3200 Aarschot],
    phone: "+32 485 58 60 57",
    // matrix: "",
    position: ("Inventor", "Theoretical Physicist"),
    website: "https://docbrownlabs.com",
    twitter: "docbrown1955",
    mastodon: "@docbrown@sciences.social",
    // github: "",
    // gitlab: "",
    linkedin: "emmett-brown-hv",
    researchgate: "emmett-brown",
    // scholar: "",
    orcid: "0000-0000-0000-1955",
  ),
  profile-picture: image("profile.jpg"),
  accent-color: rgb("#4682b4"),
  // font-color: rgb("#333333"),
  header-color: rgb("#3b4f60"),
  // date: datetime.today().display("[month repr:long] [year]"),
  // heading-font: "Fira Sans",
  // body-font: ("Noto Sans", "Roboto"),
  // body-font-size: 10.5pt,
  // paper-size: "us-letter",
  // side-width: 4cm,
  // gdpr: false,
  // footer: auto,
)
